version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:15
    container_name: bank_cards_db
    environment:
      POSTGRES_DB: bank_cards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_cards_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_cards_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_cards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - db
    networks:
      - bank_cards_network

volumes:
  postgres_data:

networks:
  bank_cards_network:
    driver: bridge