# application.yml

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: false
  application:
    name: bank-card-management-service
  
  # Настройки базы данных
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_cards_db}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  
  # Настройки JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Настройки Liquibase
  liquibase:
    change-log: classpath:/db/changelog/migration.yml
    enabled: true

# Настройки сервера
server:
  port: 8080

# Пользовательские настройки
app:
  security:
    encryption:
      algorithm: AES
      key: "pu-11-yegp-secret-key-1234567890abc"
      iv: "16-byte-iv-12345"
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:your_default_secret_key_change_it}
      expiration: ${APP_SECURITY_JWT_EXPIRATION:3600000}

# Логирование
logging:
  level:
    com.yourpackage: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/app.log
